// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/go-playground/validator/v10"
	"github.com/google/wire"
	"go-belajar-restfull/config"
	"go-belajar-restfull/controller"
	"go-belajar-restfull/middleware"
	"go-belajar-restfull/repository"
	"go-belajar-restfull/service"
	"net/http"
)

// Injectors from injector.go:

func InitializeServer() *http.Server {
	db := config.InitDB()
	employeeRepositoryImpl := repository.NewEmployeeRepository()
	validate := ProvideValidator()
	employeeServiceImpl := service.NewEmployeeService(db, employeeRepositoryImpl, validate)
	employeeControllerImpl := controller.NewEmployeeController(employeeServiceImpl)
	router := config.NewHttpRouter(employeeControllerImpl)
	apiMiddleware := middleware.NewApiMiddleware(router)
	server := config.NewHttpServer(apiMiddleware)
	return server
}

// injector.go:

var EmployeeSet = wire.NewSet(repository.NewEmployeeRepository, wire.Bind(new(repository.EmployeeRepository), new(*repository.EmployeeRepositoryImpl)), service.NewEmployeeService, wire.Bind(new(service.EmployeeService), new(*service.EmployeeServiceImpl)), controller.NewEmployeeController, wire.Bind(new(controller.EmployeeController), new(*controller.EmployeeControllerImpl)))

func ProvideValidator() *validator.Validate {
	return validator.New()
}
